# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Home
description: > # this means to ignore newlines until "baseurl:"
  A little about everything in my mind...java, devops, things i do in daily life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://skayikci.github.io" # the base hostname & protocol for your site
twitter_username: KayikciS1
github_username:  skayikci

# Build settings
markdown: kramdown

# Permalink
permalink: /:categories/:title/